name: Bug Report
description: Help us crush bugs in our software by filling out this report!
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Thoroughly describe the issue/bug.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What are you expecting the application to do?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Create a numbered list of the steps to reproduce the issue/bug.
      placeholder: |
        1. [e.g. Click on '...']
        2. [e.g. Drag and drop '...']
        3. Issue appears
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please provide screenshots of the issue/bug.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Describe what your setup/environment looks like.
      placeholder: |
        - Device: [e.g. iPhone 15 Pro, ThinkPad P15v, etc.]
        - OS: [e.g. iOS 18.7, Windows 10 22H2, etc.]
        - Browser: [e.g. Chrome, Firefox, etc.]
        - Software Version: [if applicable]
    validations:
      required: true
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any additional notes that would help narrow down and resolve the issue.
    validations:
      required: false
